version: 2
updates:
  # bun dependencies
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "fxrncyyisingithub"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
